### ISSUE TITLE
Have trouble when run Hybrid_autoencodereval.py in Stage2

### ISSUE THREAD

**Issue by khanhhoaa19** [Benny0323/BS-Diff#1]
When I run Hybrid_autoencodereval.py I have a trouble 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 11
      9 input = myTransform(input).to(device)  # 256 * 256
     10 input = torch.unsqueeze(input, dim=-3)
---> 11 reconstruction, _, _ = model(input)
     12 reconstruction = torch.squeeze(reconstruction, dim=-3)
     13 reconstruction = np.array(reconstruction.detach().to("cpu"))

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /opt/conda/lib/python3.10/site-packages/generative/networks/nets/autoencoderkl.py:787, in AutoencoderKL.forward(self, x)
    786 def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
--> 787     z_mu, z_sigma = self.encode(x)
    788     z = self.sampling(z_mu, z_sigma)
    789     reconstruction = self.decode(z)

File /opt/conda/lib/python3.10/site-packages/generative/networks/nets/autoencoderkl.py:726, in AutoencoderKL.encode(self, x)
    718 def encode(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    719     """
    720     Forwards an image through the spatial encoder, obtaining the latent mean and sigma representations.
    721 
   (...)
    724 
    725     """
--> 726     if self.use_checkpointing:
    727         h = torch.utils.checkpoint.checkpoint(self.encoder, x, use_reentrant=False)
    728     else:

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'AutoencoderKL' object has no attribute 'use_checkpointing'

**Comment by Benny0323** [comment]
Thanks for your question. I think maybe this website may help you find out the reason.
Actually, I cannot give you a clear explanation now due to limited error information.
https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/networks/nets/autoencoderkl.py

**Comment by Benny0323** [comment]
[khanhhoaa19](https://github.com/khanhhoaa19) Do you solved it?

**Comment by khanhhoaa19** [comment]
@Benny0323 I have tried, but currently it still hasn't been resolved

**Comment by Benny0323** [comment]
@khanhhoaa19 
https://github.com/apple/ml-stable-diffusion/issues/155
I find that this person has the same problem as you. 
Maybe a few days later I will try running it again on my personal computer.

**Comment by khanhhoaa19** [comment]
Thank you so much, @Benny0323

**Comment by khanhhoaa19** [comment]
I tried running it on a different computer, but the issue persists

**Comment by Benny0323** [comment]
@khanhhoaa19 OK, I will try it next week. This weekend, I will be very busy. Thanks!

**Comment by khanhhoaa19** [comment]
Hi @Benny0323, did you solve the problem? I think it was wrong when loading the checkpoint to predict.

**Comment by Benny0323** [comment]
Hi @khanhhoaa19 today I run it on my laptop using cpu, it succeeds! 
<img width="1512" alt="截屏2024-04-17 18 50 06" src="https://github.com/Benny0323/BS-Diff/assets/104205136/b14eee64-04a1-4955-8574-757df31c4f79">

**Comment by khanhhoaa19** [comment]
Hi @Benny0323 I think you should try with a new environment because when I try another computer, the issue persists.

**Comment by Benny0323** [comment]
I use the different environment.
Originally I run it in GPU cluster



發自我的iPhone


------------------ Original ------------------
From: khanhhoaa19 ***@***.***&gt;
Date: Wed,Apr 17,2024 6:53 PM
To: Benny0323/BS-Diff ***@***.***&gt;
Cc: Zhanghao Chen ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Benny0323/BS-Diff] Have trouble when runHybrid_autoencodereval.py in Stage2 (Issue #1)





 
Hi @Benny0323 I think you should try with a new environment because when I try another computer, the issue persists.

**Comment by khanhhoaa19** [comment]
Oh, I use the environment from your requirements.txt. Can you share with me the environment you used?

**Comment by Benny0323** [comment]
Ok, what is your torch version?

**Comment by Benny0323** [comment]
I think you should use torch version 2.0.1

**Comment by khanhhoaa19** [comment]
Thank you I will downgrade version pytorch

**Comment by Benny0323** [comment]
@khanhhoaa19 Do you successfully run it?
