### ISSUE TITLE
 AttributeError: 'AutoencoderKL' object has no attribute 'use_checkpointing'

### ISSUE THREAD

**Issue by Henrik-hw** [Benny0323/BS-Diff#2]
Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: NOT INSTALLED or UNKNOWN VERSION.
scikit-image version: 0.22.0
scipy version: 1.13.1
Pillow version: 10.0.1
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.15.2+cu117
tqdm version: 4.65.2
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: 2.1.4
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.
clearml version: NOT INSTALLED or UNKNOWN VERSION.

**I installed the relevant dependencies according to the requirements.txt you provided, and an error occurred in Stage2: AttributeError: 'AutoencoderKL' object has no attribute 'use_checkpointing'**

**Comment by Benny0323** [comment]
I think you should use Torch version 2.0.1. See https://github.com/Benny0323/BS-Diff/issues/1

**Comment by Henrik-hw** [comment]
my torch version is torch                    2.0.1
but still have the same problem


Using cuda
Traceback (most recent call last):
  File "/data1/BS-Diff-main/Stage2/Hybrid_autoencodereval.py", line 81, in <module>
    reconstruction, _, _ = model(input)
  File "/home/medical1/anaconda3/envs/medical1_bs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/medical1/anaconda3/envs/medical1_bs/lib/python3.9/site-packages/generative/networks/nets/autoencoderkl.py", line 787, in forward
    z_mu, z_sigma = self.encode(x)
  File "/home/medical1/anaconda3/envs/medical1_bs/lib/python3.9/site-packages/generative/networks/nets/autoencoderkl.py", line 726, in encode
    if self.use_checkpointing:
  File "/home/medical1/anaconda3/envs/medical1_bs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AutoencoderKL' object has no attribute 'use_checkpointing'

**Comment by Benny0323** [comment]
I suggest you looking detailed codes in generative/networks/nets/autoencoderkl.py.
Here is the link: https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/networks/nets/autoencoderkl.py
And I hope it can be solved.

**Comment by Henrik-hw** [comment]
Is the saved model missing the use_checkpointing attribute?

**Comment by Henrik-hw** [comment]
I have tried many solutions to the problem, but none of them worked. I guess there was a problem when saving the model.

**Comment by Henrik-hw** [comment]
> I suggest you looking detailed codes in generative/networks/nets/autoencoderkl.py. Here is the link: https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/networks/nets/autoencoderkl.py And I hope it can be solved.

I have tried many solutions to the problem, but none of them worked. I guess there was a problem when saving the model.

**Comment by Benny0323** [comment]
I'm so sorry about that. Maybe you can use the JSRT dataset to train the model and test it. Good luck!
